version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-comercio
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: usuario_db
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-comercio
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1234

  mysql:
    image: mysql:latest
    container_name: mysql-comercio
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: inventario_db
    ports:
      - "3307:3306"
