version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres-comercio
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: usuario_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-comercio
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1234

  mysql:
    image: mysql:latest
    container_name: mysql-comercio
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: inventario_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  user_service:
    build:
      context: ./User_Service
    container_name: user_service

  inventario_service:
    build:
      context: ./Inventario_Service
    container_name: inventario_service

  gateway_service:
    build:
      context: ./Api_Gateway
    container_name: api_gateway

volumes:
  postgres_data:
  mysql_data:



